version: '3.9'
services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx.Dockerfile
    args:
      nginx_domain: admn.cotami.jp
    ports:
      - 80:80

  web:
    build:
      context: .
      args:
        build_command: build
    stdin_open: true
    tty: true
    ports:
      - 5050:5050
    environment:
      - NODE_ENV=production
